.github/
  copilot-instructions.md
  dh-context.default.md
  skills/
    dh-branch/SKILL.md
.gitignore
README.md
knowledge/
  README.md


---
# Generated by the DH Champion extension
.github/dh-context.md
.vscode/

--
# Working in this workspace

This workspace contains our Azure DevOps repositories and the shared AI assets
that drive spec driven development.

Read [workspace context](dh-context.md) for the repository list, base branches
and branch naming pattern. Always use it rather than assuming.

## Conventions

- Always branch from a repository's base branch, never from another feature branch.
- Use the Azure DevOps tools to read work items rather than guessing their contents.
- Analysis documents live in the `knowledge` folder. Consult them before changing
  database access, pipelines or API contracts.


    ---


    ---
name: dh-branch
description: Create a feature branch for an Azure DevOps work item, from the correct base branch, using our naming convention.
---

# Create a feature branch

Use this skill when the user wants to start work on an Azure DevOps work item.

## Inputs

- A work item ID. If the user did not give one, ask for it before doing anything else.
- The target repository. If the user did not name one, ask which repository to use.

## Steps

1. Read [workspace context](../../dh-context.md) for the repository list, their base
   branches, and the feature branch pattern. Never assume these values.
2. Read the work item from Azure DevOps to get its title and type. Do not guess the title.
3. Build a slug from the title: lowercase, spaces and punctuation replaced with hyphens,
   trimmed to at most 50 characters, with no trailing hyphen.
4. Build the branch name from the pattern in the context file, substituting
   `{workItemId}` with the work item ID and `{title}` with the slug.
5. In the chosen repository, run in order:
   - `git fetch origin`
   - `git checkout <base branch>`
   - `git pull`
   - `git checkout -b <branch name>`
6. Report the branch created, the base branch it came from, and the work item title.

## Rules

- Never branch from a branch other than the repository's base branch.
- Never push the branch. The user decides when to push.
- If the branch already exists, stop and tell the user.
- If the work item cannot be found, stop and report it. Do not invent a title.


  ---


  # Workspace context

Fallback copy. Normally the DH Champion extension generates `dh-context.md`
from your settings. If you are setting up by hand, copy this file to
`dh-context.md` in the same folder.

- Azure DevOps organization: `your-org-name`
- Default project: `YourProjectName`
- Feature branch pattern: `feature/{workItemId}-{title}`

## Repositories

| Repository | Project | Base branch |
| --- | --- | --- |
| RepoOne | YourProjectName | develop |
| RepoTwo | YourProjectName | develop |
| RepoThree | YourProjectName | develop |
| RepoFour | YourProjectName | develop |



  -----


  "dhChampion.sharedRepository": {
  "type": "string",
  "default": "dh-champion-shared",
  "description": "Azure DevOps repository holding the shared AI assets and knowledge base."
}


---

  

  
  
  
