// Generates the AI assets into the primary workspace folder's .github directory.
// These files are regenerated on every Setup run, so local edits do not survive.
function writeAiAssets(folder: string, repos: Repo[], branchPattern: string, version: string): string[] {
  const githubDir = path.join(folder, ASSETS_FOLDER, '.github');
  const written: string[] = [];

  // Always-on context for Copilot in this workspace.
  const repoTable = repos
    .map(r => `| ${r.name} | ${r.project ?? ADO_PROJECT} | ${r.baseBranch ?? DEFAULT_BASE_BRANCH} |`)
    .join('\n');

  const copilotInstructions = `# Working in this workspace

This workspace contains our Azure DevOps repositories and the shared AI assets
that drive spec driven development. It is generated by the DH Champion extension.

## Repositories

| Repository | Project | Base branch |
| --- | --- | --- |
${repoTable}

## Conventions

- Azure DevOps organization: \`${ADO_ORGANIZATION}\`
- Feature branches follow the pattern \`${branchPattern}\`
- Always branch from the repository's base branch shown above, never from another feature branch.
- Use the Azure DevOps tools to read work items rather than guessing their contents.
`;

  fs.mkdirSync(githubDir, { recursive: true });
  fs.writeFileSync(path.join(githubDir, 'copilot-instructions.md'), copilotInstructions, 'utf8');
  written.push('copilot-instructions.md');

  // Skill: create a feature branch from the correct base branch.
  const branchSkillDir = path.join(githubDir, 'skills', 'ai-branch');
  const branchSkill = `---
name: ai-branch
description: Create a feature branch for an Azure DevOps work item, from the correct base branch, using our naming convention.
---

# Create a feature branch

Use this skill when the user wants to start work on an Azure DevOps work item.

## Inputs

- A work item ID. If the user did not give one, ask for it before doing anything else.
- The target repository. If the user did not name one, ask which of the repositories below to use.

## Repositories and their base branches

| Repository | Project | Base branch |
| --- | --- | --- |
${repoTable}

## Steps

1. Read the work item from Azure DevOps to get its title and type. Do not guess the title.
2. Build a slug from the title: lowercase, spaces and punctuation replaced with hyphens,
   trimmed to at most 50 characters, with no trailing hyphen.
3. Build the branch name from the pattern \`${branchPattern}\`, substituting:
   - \`{workItemId}\` with the work item ID
   - \`{title}\` with the slug from step 2
4. In the chosen repository, run these commands in order:
   - \`git fetch origin\`
   - \`git checkout <base branch>\`
   - \`git pull\`
   - \`git checkout -b <branch name>\`
5. Report the branch you created, the base branch it came from, and the work item title.

## Rules

- Never branch from a branch other than the base branch listed above.
- Never push the branch. The user decides when to push.
- If the branch already exists, stop and tell the user rather than creating a variation.
- If the work item cannot be found, stop and report it. Do not invent a title.
`;

  fs.mkdirSync(branchSkillDir, { recursive: true });
  fs.writeFileSync(path.join(branchSkillDir, 'SKILL.md'), branchSkill, 'utf8');
  written.push('skills/ai-branch');

  // Version stamp, so we can detect drift later.
  fs.writeFileSync(
    path.join(githubDir, 'dh-champion.json'),
    JSON.stringify({ version, generatedAt: new Date().toISOString(), assets: written }, null, 2),
    'utf8'
  );

  log.appendLine(`✔ AI assets written: ${githubDir}`);
  log.appendLine(`   ${written.join(', ')}`);
  return written;
}
